#!/bin/sh
#Cross_Cancer_Sharing_smartEnh
#PBS -q normal
#PBS -P personal
#PBS -l select=2:ncpus=24:mem=96G:mpiprocs=24:ompthreads=1
#PBS -l walltime=24:00:00
#PBS -N Cross_Cancer_Sharing_smartEnh
# 设置CANCERS结果的文件夹路径,目的是获得之前用bowtie1跑出来的*.unmapped.fastq

module load bowtie/1.1.2
module load bowtie2/2.29
module load samtools/1.3
module load bedtools/2.25

export CANCERS="/home/users/nus/csijy/scratch/cistromeTissue/CANCERS"
export SCAFFOLD="/home/users/nus/csijy/scratch/cistromeTissue/Scaffold_Dev"
export Enhancers="/home/users/nus/csijy/scratch/cistromeTissue/Enhancers"
export Cross_Cancer_Sharing_smartEnh="/home/users/nus/csijy/scratch/cistromeTissue/Cross_Cancer_Sharing_smartEnh"
declare -A k27ac=(
["DGC_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5278784_1.fastq"
["BTIC_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5278783_1.fastq"
["tamoxifen_EC12_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5198790.fastq"
["tamoxifen_EC11_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5198789.fastq"
["tamoxifen_EC10_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5198788.fastq"
["tamoxifen_EC9_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5198787.fastq"
["tamoxifen_EC8_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5198786.fastq"
["tamoxifen_EC7_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5198785.fastq"
["tamoxifen_EC6_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5198784.fastq"
["tamoxifen_EC5_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5198783.fastq"
["tamoxifen_EC4_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5198782.fastq"
["tamoxifen_EC3_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5198781.fastq"
["tamoxifen_EC2_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5198780.fastq"
["tamoxifen_EC1_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5198779.fastq"
["CLL2070_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5123606.fastq"
["CLL1993_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5123605.fastq"
["CLL2062_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5123603.fastq"
["CLL2040_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5123601.fastq"
["CLL1958_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5123599.fastq"
["CLL1239_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5123597.fastq"
["CLL702_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5123595.fastq"
["CLL1252_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5123593.fastq"
["CLL1863_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR5123591.fastq"
["SU_DIPG_IV2_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR4014879.fastq"
["SU_DIPG_IV1_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR4014878.fastq"
["RH5_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3720791.fastq"
["RH4_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3720774.fastq"
["RD_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3720765.fastq"
["NS134_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3720763.fastq"
["NS129_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3720761.fastq"
["NCI0082_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3720759.fastq"
["NCI0075_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3720757.fastq"
["CTR_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3720755.fastq"
["non-tamoxifen_EC3_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3480369.fastq"
["non-tamoxifen_EC5_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3480365.fastq"
["non-tamoxifen_EC4_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3480359.fastq"
["non-tamoxifen_EC1_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3480355.fastq"
["non-tamoxifen_EC2_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3480351.fastq"
["Be2-C_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR3363251.fastq"
["753T_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2969519.fastq"
["753N_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2969518.fastq"
["750T_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2969517.fastq"
["750N_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2969516.fastq"
["T24_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2946617.fastq"
["5637_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2946615.fastq"
["J82_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2946613.fastq"
["RT308_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2133475.fastq"
["RT407_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2133472.fastq"
["RT262_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2133469.fastq"
["RT242_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2133466.fastq"
["RT236_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2133463.fastq"
["RT230_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2133458.fastq"
["RT172_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR2133455.fastq"
["prefrontal_cortex1_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1979001.fastq"
["prefrontal_cortex2_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1978995.fastq"
["Putamen_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1978992.fastq"
["Thalamic_nuclei_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1978989.fastq"
["Caudate_nucleus_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1978986.fastq"
["White_Matter_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1978983.fastq"
["Occipital_Pole_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1978980.fastq"
["FL17_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1610188.fastq"
["FL16_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1610186.fastq"
["FL14_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1610180.fastq"
["FL11_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1610174.fastq"
["FL10_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1610171.fastq"
["FL8_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1610165.fastq"
["FL5_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1610159.fastq"
["FL2_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1610150.fastq"
["FL1_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1610148.fastq"
["P14A_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1020512.fastq"
["P107A_H3K27ac"]="/home/users/nus/csijy/scratch/data/SRR1020510.fastq"
)

cd $Cross_Cancer_Sharing_smartEnh

samtools view -h /home/projects/11000451/chip-seq/data/IndelautoPairedSample/CANCERS2/N2000085_H3K27ac.sorted.bam| head -n 27 > header

for file in "${!k27ac[@]}"

do
  echo $file
  export readFile="$CANCERS/$file.all_chroms.psl.real.filt.sam"
  export scaFile="$SCAFFOLD/$file.all_chroms.psl.real.filt.sam"
  
#allFile
  cat $readFile $scaFile | grep -v "chrM" > $file.tmp.sam
  cat header $file.tmp.sam > $file.sam
  samtools view -b $file.sam > $file.bam
  
  intersectBed -a $file.bam -b $Enhancers/$file\_peaks.bed > $file.inPeaks.bam
  samtools view $file.inPeaks.bam > $file.inPeaks.sam

#readFile
  cat header $readFile > $file.read.sam
  samtools view -b $file.read.sam > $file.read.bam

  intersectBed -a $file.read.bam -b $Enhancers/$file\_peaks.bed > $file.read.inPeaks.bam
  samtools view $file.read.inPeaks.bam > $file.read.inPeaks.sam
  
#scaFile
  cat header $scaFile > $file.sca.sam
  samtools view -b $file.sca.sam > $file.sca.bam
  intersectBed -a $file.sca.bam -b $Enhancers/$file\_peaks.bed > $file.sca.inPeaks.bam

  
  samtools view $file.sca.inPeaks.bam > $file.sca.inPeaks.sam
  perl filter_sam_by_string.pl $file.inPeaks.sam > $file.inPeaks.bed
  perl filter_sam_by_string.pl $file.tmp.sam > $file.bed
  perl filter_sam_by_string.pl $file.read.sam > $file.read.bed
  perl filter_sam_by_string.pl $file.sca.sam > $file.sca.bed
  perl filter_sam_by_string.pl $file.sca.inPeaks.sam > $file.sca.inPeaks.bed
  perl filter_sam_by_string.pl $file.read.inPeaks.sam > $file.read.inPeaks.bed

# 
  awk -F\\t '{print $1 "_" $2 "_" $3 "_" $4}' $file.inPeaks.bed | sort | uniq > $file.inPeaks.unique.txt
  awk -F\\t '{print $1 "_" $2 "_" $3 "_" $4}' $file.inPeaks.bed | sort | uniq | sed s/\_/\\t/g > $file.inPeaks.unique.bed
  awk -F\\t '{print $1 "_" $2 "_" $3 "_" $4}' $file.bed | sort | uniq > $file.unique.txt
  awk -F\\t '{print $1 "_" $2 "_" $3 "_" $4}' $file.bed | sort | uniq | sed s/\_/\\t/g > $file.unique.bed
  awk -F\\t '{print $1 "_" $2 "_" $3 "_" $4}' $file.read.bed | sort | uniq | sed s/\_/\\t/g > $file.read.unique.bed
  awk -F\\t '{print $1 "_" $2 "_" $3 "_" $4}' $file.sca.bed | sort | uniq | sed s/\_/\\t/g > $file.sca.unique.bed


  rm $file.sam $file.bam $file.tmp.sam $file.inPeaks.bed $file.inPeaks.bam $file.inPeaks.sam
  
done

cd $Enhancers

for file in "${!k27ac[@]}"
do
  echo $file
  export ins="$Cross_Cancer_Sharing_smartEnh/$file.bed"
  export insUniq="$Cross_Cancer_Sharing_smartEnh/$file.unique.bed"
  
  intersectBed -wa -c -a $ins -b $file\_peaks.bed > $file.txt
  intersectBed -wa -c -a $ins -b $file\_peaks.bed > $file.unique.txt

done

